import React from 'react';
import * as XLSX from 'xlsx/xlsx.mjs';


const data = [
    
    {
        DEPARTAMENTO: 'BOLIVAR', MUNICIPIO: 'MAGANGUE', CONTRIBUYENTE: 'GRUPO EXITO - MAGANGUE', NIT: 8909006089, TIPO_CLIENTE: 'ANTIGUO',
        FACTURA: '10112022 - 29', VALOR_FACTURA: '$ 8.064.990', FECHA_FACTURA: '25/01/2023', FECHA_ENTREGA: '25/01/2023', FECHA_VENCIMIENTO: '24/02/2023',
        PERIODO: '202211', TIPO_FACT: 'CONSUMO', COMERCIALIZADOR: 'EMGESA S.A. E.S.P.', FACTURADO_POR: 'RESOLUCION', ESTADO_FACTURA: 'PENDIENTE ENVIO',
        OBSERV_FACTURA: '', VALOR_RECAUDO: '17400000', CARTERA_FECHA: '2320000',
        CARTERA_VENCIDA: '0', FECHA_RECA_SOPORTE: '8/02/2023', FECHA_RECA_BITACORA: '8/02/2023', ESTADO_RECAUDO: 'PAGADO', OBSERV_RECAUDO: '',
    },
    {
        DEPARTAMENTO: 'BOLIVAR', MUNICIPIO: 'MAGANGUE', CONTRIBUYENTE: 'GRUPO EXITO - MAGANGUE', NIT: 8909006089, TIPO_CLIENTE: 'ANTIGUO',
        FACTURA: '10112022 - 29', VALOR_FACTURA: '$ 8.064.990', FECHA_FACTURA: '25/01/2023', FECHA_ENTREGA: '25/01/2023', FECHA_VENCIMIENTO: '24/02/2023',
        PERIODO: '202211', TIPO_FACT: 'CONSUMO', COMERCIALIZADOR: 'EMGESA S.A. E.S.P.', FACTURADO_POR: 'RESOLUCION', ESTADO_FACTURA: 'PENDIENTE ENVIO',
        OBSERV_FACTURA: '', VALOR_RECAUDO: '17400000', CARTERA_FECHA: '2320000',
        CARTERA_VENCIDA: '0', FECHA_RECA_SOPORTE: '8/02/2023', FECHA_RECA_BITACORA: '8/02/2023', ESTADO_RECAUDO: 'PAGADO', OBSERV_RECAUDO: '',
    },
    {
        DEPARTAMENTO: 'BOLIVAR', MUNICIPIO: 'MAGANGUE', CONTRIBUYENTE: 'GRUPO EXITO - MAGANGUE', NIT: 8909006089, TIPO_CLIENTE: 'ANTIGUO',
        FACTURA: '10112022 - 29', VALOR_FACTURA: '$ 8.064.990', FECHA_FACTURA: '25/01/2023', FECHA_ENTREGA: '25/01/2023', FECHA_VENCIMIENTO: '24/02/2023',
        PERIODO: '202211', TIPO_FACT: 'CONSUMO', COMERCIALIZADOR: 'EMGESA S.A. E.S.P.', FACTURADO_POR: 'RESOLUCION', ESTADO_FACTURA: 'PENDIENTE ENVIO',
        OBSERV_FACTURA: '', VALOR_RECAUDO: '17400000', CARTERA_FECHA: '2320000',
        CARTERA_VENCIDA: '0', FECHA_RECA_SOPORTE: '8/02/2023', FECHA_RECA_BITACORA: '8/02/2023', ESTADO_RECAUDO: 'PAGADO', OBSERV_RECAUDO: '',
    }
]

const ExcelReporteClientesEspeciales = () => {

    const DescargarExcelReporteClientesEspeciales = () => {
        let workBook = XLSX.utils.book_new()
        let workSheet = XLSX.utils.json_to_sheet(data)

        XLSX.utils.book_append_sheet(workBook, workSheet, 'MySheet')
        XLSX.writeFile(workBook, 'Reporte de clientes especiales.xlsx')
    }

    return (
        <div>
            <h2>Descargar excel reporte de clientes especiales</h2>
            <button onClick={() => DescargarExcelReporteClientesEspeciales()}>Descargar</button>
        </div>
    );
}

export default ExcelReporteClientesEspeciales;
